#%RAML 1.0
title: My Users API

uses:
  traitsLibrary: TraitsLibrary.raml
  user: User.raml

/users:
  get:
    queryParameters:
      type:
        required: false
        enum:
          - USER
          - ADMIN
    is: [traitsLibrary.usersResponseMessage]

  post:
    body:
      application/json:
        type: user.usertype
        examples: !include UserNoIdExample.raml
    is: [traitsLibrary.postResponseMessage]

  /{id}:
    get:
      is: [traitsLibrary.getByIdResponseMessage]
    
    delete:
      is: [traitsLibrary.deleteByIdResponseMessage]
    
    patch:
      body:
        application/json:
          type: user.usertype
          examples: !include UserNoIdExample.raml
      is: [traitsLibrary.patchByIdResponseMessage]